name: Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:

      # 1. 소스 받기
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      # 4. 시스템 패키지
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            python3-pip python3-setuptools \
            autoconf automake libtool libltdl-dev \
            pkg-config zlib1g-dev libncurses-dev \
            libtinfo5 libffi-dev libssl-dev \
            build-essential ccache patch

      # 5. Buildozer
      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36 virtualenv
          pip install \
          git+https://github.com/kivy/python-for-android.git

      # 7. 디버그
      - name: Check environment
        run: |
          java -version
          python --version
          echo $JAVA_HOME

      # 8. Build APK
      - name: Build APK
        shell: bash
        run: |
          set -o pipefail
          yes | buildozer -v android debug 2>&1 | tee build.log

      # 9. APK 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ldr-apk
          path: bin/*.apk
          if-no-files-found: error

      # 10. 로그 업로드
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
          if-no-files-found: warn